package pava.lang;

/**
 * Unified closure invocation interface for Pava language.
 * All closures generated by Pava compiler implement this interface.
 * 
 * Design per Pava closure specification:
 * - Single call method accepting Object... args for flexibility
 * - Returns Object which can be cast to the expected return type
 * - Used with LambdaMetafactory for efficient JVM lambda generation
 */
@FunctionalInterface
public interface Callable {
    
    /**
     * Invoke the closure with the given arguments.
     * 
     * @param args Arguments passed to the closure
     * @return The closure's return value (null for void closures)
     */
    Object call(Object... args);
    
    /**
     * Invoke the closure with no arguments.
     * Convenience method for closures with no parameters.
     * 
     * @return The closure's return value
     */
    default Object call() {
        return call(new Object[0]);
    }
    
    /**
     * Invoke the closure with a single argument.
     * Convenience method for single-parameter closures.
     * 
     * @param arg The argument to pass
     * @return The closure's return value
     */
    default Object call(Object arg) {
        return call(new Object[] { arg });
    }
}